config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'

  get 'errors/internal_server_error'

  devise_for :admins
  devise_for :users

  resources :workshops

  namespace :workshops do
    get ':workshop_id/books/new' => 'books#new', as: 'new_book'
    get 'books/all' => 'books#index'
    get 'book/:id' => 'books#show', as: 'show_book'
    delete 'book/:id' => 'books#delete'
    post ':workshop_id/books/new' => 'books#create'
    get 'search/results' => 'search#index'
  end

  get 'user/:id/profile' => 'users#show', as: 'user_profile'

  namespace :admin do 
    resources :users
  end

  namespace :users do
    resources :workshops
  end

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  root 'workshops#index', as: 'home'
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_one :workshop

  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/models/workshop.rb
class Workshop < ApplicationRecord
   mount_uploaders :images, WorkshopGalleryUploader
   validate :images_limit_number, :images_size_validation

   belongs_to :user
   has_many :books, dependent: :destroy

  validates :title,
        presence: true,
        length: { minimum: 5, too_short: "%{count} characters is the minium"},
        length: { maximum: 60, too_long: "%{count} characters is the maximum"},
        case_sensitive: false

  validates :description,
            presence: true

  validates :address,
            presence: true

  validates :price,
            presence: true,
            numericality: { greater_than_or_equal_to: 1 }

  validates :artists_max,
          presence: true,
          numericality: { greater_than_or_equal_to: 1 }

  validates :images, presence: { message: "You need to add at least one image" }

  # Limit size of the image
  private def images_size_validation
    return if images.blank?
    images.each do |image|
      errors[:images] << "Should be less than 1 MO" if image.size > 1.megabytes
    end
  end

  private def images_limit_number 
    return if images.blank?
    errors[:images] << "You can't add more than 4 images" if images.size > 4
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
  end

  def show
  end

  def create 
  end 
end

app/controllers/users/workshops_controller.rb
class Users::WorkshopsController < WorkshopsController
  before_action :authenticate_user!

  def index
    @workshops = Workshop.where(user_id: current_user.id).limit(100)
  end
end

app/controllers/workshops/books_controller.rb
class Workshops::BooksController < BooksController 
  before_action :find_workshop!, only: [:new, :create]
  before_action :authenticate_user!

  def index
    select = 'workshops.title, workshops.price, books.id, books.total_price, books.start_date, books.end_date'
    @books_all = Book.select(select).joins('INNER JOIN workshops ON books.workshop_id = workshops.id').where(user_id: current_user.id).all
    @books_previous = Book.select(select).joins('INNER JOIN workshops ON books.workshop_id = workshops.id').where(user_id: current_user.id).where('end_date < ?', DateTime.now).all
    @books_coming = Book.select(select).joins('INNER JOIN workshops ON books.workshop_id = workshops.id').where(user_id: current_user.id).where('end_date > ?', DateTime.now).all
  end

  def show
    @book = Book.find(params[:id])
    @workshop = Workshop.find(@book.workshop_id)
  end

  def new 
    @title = 'Book an workshop'
    Book.where(workshop_id: @workshop.id).find_each do |book|
      @dates ||= []
      @dates.push({start: book.start_date, end: book.end_date})
    end 
    @dates = @dates.to_json
  end 

  def create
    total_price = (params[:end_date].to_i - params[:start_date].to_i) * @workshop.price
    @book = current_user.books.new(book_params.merge(total_price: total_price))
    if @book.save
      redirect_to :workshops_books_all
    else 
      redirect_to :workshops_new_book
    end
  end 

  def delete
    @book = Book.find(params[:id])
    @book.destroy
    respond_to do |format|
      format.html { redirect_to workshops_books_all_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def destroy
  end

  private 
    def find_workshop!
      @workshop = Workshop.where(id: params[:workshop_id]).first
      puts "Find workshop : " + @workshop.inspect
    end

    def book_params
      params.permit(:start_date, :end_date, :artists, :workshop_id)
    end
end

app/controllers/workshops/search_controller.rb
class Workshops::SearchController < SearchController

  def index
    if params[:keyword].empty?
      redirect_to :workshops
    else 
      @keyword = params[:keyword]
    end

    @workshops = Workshop.where('title LIKE ?', "%#{@keyword}%").limit(100)

    if @workshops.empty? 
      @no_results = 'There is no results for your query'
    end
  end

end

app/controllers/workshops_controller.rb
class WorkshopsController < ApplicationController
  before_action :set_workshop, only: [:show]

  # GET /workshops
  # GET /workshops.json
  def index
    @workshops = Workshop.all
  end

  # GET /workshops/new
  def new
    @workshop = Workshop.new
  end

  def edit 
    @workshop = Workshop.find(params[:id])
  end

  # POST /workshops
  # POST /workshops.json
  def create
    @workshop = current_user.workshops.new(workshop_params)

    respond_to do |format|
      if @workshop.save
        format.html { redirect_to @workshop, notice: 'Workshop was successfully created.' }
        format.json { render :show, status: :created, location: @workshop }
      else
        format.html { render new_users_workshop_path }
        format.json { render json: @workshop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workshops/1
  # PATCH/PUT /workshops/1.json
  def update
    @workshop = Workshop.find(params[:id])
    
    respond_to do |format|
      if @workshop.update(workshop_params)
        format.html { redirect_to @workshop, notice: 'Workshop was successfully updated.' }
        format.json { render :show, status: :ok, location: @workshop }
      else
        format.html { render :edit }
        format.json { render json: @workshop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workshops/1
  # DELETE /workshops/1.json
  def destroy
    @workshop = Workshop.find(params[:id])
    @workshop.destroy
    respond_to do |format|
      format.html { redirect_to users_workshops_url, notice: 'Workshop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  #   # Use callbacks to share common setup or constraints between actions.
    def set_workshop
      @workshop = Workshop.find(params[:id])
      @user = User.find(@workshop.user_id)
      @title = @workshop.title;
      puts 'User' + @user.inspect
    end

  #   # Never trust parameters from the scary internet, only allow the white list through.
    def workshop_params
      params.require(:workshop).permit(:title, :description, :address, :price, :lat, :lng, :artists_max, {images: []}, {art_types: []})
    end
end

app/helpers/workshops_helper.rb
module WorkshopsHelper
end

app/views/workshops/books/index.html.erb
<div class="container">
  <h1>My books</h1>

  <%= content_tag(:div, notice, :class => "card-panel green darken-1 white-text") if notice %>

  <% if @books_all.empty? %>
    <div class="card-panel">
      <span class="blue-text text-darken-2">
        <div>
          You have no bookings
        </div>
        <br>
        <div>
          <%= link_to 'Find an workshop', home_path, class: "btn" %>
        </div>
      </span>
    </div>
  <% else %>   
    <div class="row">
      <div class="col s12">
        <ul class="tabs">
          <li class="tab col s4"><a class="active" href="#test1">All bookings</a></li>
          <li class="tab col s4"><a  href="#test2">Coming bookings</a></li>
          <li class="tab col s4"><a href="#test3">Previous bookings</a></li>
        </ul>
      </div>
    </div>

    <table>
      <thead>
        <tr>
          <th>Title</th>
          <th>Start date</th>
          <th>End date</th>
          <th>Duration</th>
          <th>Total price</th>
        </tr>
      </thead>
    
      <tbody id="test1">
        <% @books_all.each do |book| %>
          <tr>
            <td><%= link_to book.title, workshops_show_book_path(book) %></td>
            <td><%= book.start_date.to_formatted_s(:long)  %></td>
            <td><%= book.end_date.to_formatted_s(:long)  %></td>
            <td><%= distance_of_time_in_words(book.start_date, book.end_date) %></td>
            <td><%= book.total_price.to_s + ' €' %></td>
          </tr>
        <% end %>
      </tbody>

      <tbody id="test2">
        <% @books_coming.each do |book| %>
          <tr>
            <td><%= link_to book.title, workshops_show_book_path(book) %></td>
            <td><%= book.start_date.to_formatted_s(:long)  %></td>
            <td><%= book.end_date.to_formatted_s(:long)  %></td>
            <td><%= distance_of_time_in_words(book.start_date, book.end_date) %></td>
            <td><%= book.total_price.to_s + ' €' %></td>
          </tr>
        <% end %>
      </tbody>

      <tbody id="test3">
        <% @books_previous.each do |book| %>
          <tr>
            <td><%= link_to book.title, workshops_show_book_path(book) %></td>
            <td><%= book.start_date.to_formatted_s(:long)  %></td>
            <td><%= book.end_date.to_formatted_s(:long)  %></td>
            <td><%= distance_of_time_in_words(book.start_date, book.end_date) %></td>
            <td><%= book.total_price.to_s + ' €' %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
  <br>
</div>

app/views/workshops/books/new.html.erb
<div class="container book__page-new">
  <h1>Book an workshop</h1>
  
  <%= form_with(model: @book, local: true) do |form| %>
  
    <div class="field">
      <%= form.hidden_field :end_date, :class => "end__date" %>
    </div>
  
    <div class="field">
      <%= form.hidden_field :start_date, :class => "start__date" %>
    </div>
  
    <%= content_tag :div, @dates, class: "hidden", id: "books_data"%>
  
    <label>Choose a date range</label>
    <input type="text" class="daterange" value=""/>
  
    <div class="total__price"></div>
    <div class="total__days"></div>
    <div class="day__price hidden">
      <%= @workshop.price %>
    </div>

    <% if @workshop.artists_max.present? %>
      <div class="field">
        <label>How many artists ?</label>
        <%= form.select(:artists, options_for_select(1..@workshop.artists_max)) %>
      </div>
    <% end %>
  
    <div class="actions">
      <%= form.submit("Book", {:class => "btn"}) %>
    </div>
  <% end %>
</div>

app/views/workshops/books/show.html.erb
<div class="container book__page-show">
  <h1>My book summary</h1>
  
  <div class="field">
    <strong> Booking of :</strong>
    <%= link_to @workshop.title, workshop_path(@workshop) %>
  </div>
  
  <div class="dates field">
    <div class="dates__start">
      <strong>Arrive date : </strong>
      <%= time_tag(@book.start_date) %>
    </div>
     <div class="dates__end">
      <strong>Leave date : </strong>
      <%= time_tag(@book.end_date) %>
    </div>
  </div>
  
  <div class="price field">
    <strong>Total price : </strong>
    <%= @book.total_price %> €
  </div>
  
  <%= link_to 'Cancel', workshops_show_book_path(@book), method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn red" %>
  
</div>