config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'

  get 'errors/internal_server_error'

  devise_for :admins
  devise_for :users

  resources :workshops

  namespace :workshops do
    get ':workshop_id/books/new' => 'books#new', as: 'new_book'
    get 'books/all' => 'books#index'
    get 'book/:id' => 'books#show', as: 'show_book'
    delete 'book/:id' => 'books#delete'
    post ':workshop_id/books/new' => 'books#create'
    get 'search/results' => 'search#index'
  end

  get 'user/:id/profile' => 'users#show', as: 'user_profile'

  namespace :admin do 
    resources :users
  end

  namespace :users do
    resources :workshops
  end

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  root 'workshops#index', as: 'home'
end

app/models/workshop.rb
class Workshop < ApplicationRecord
   mount_uploaders :images, WorkshopGalleryUploader
   validate :images_limit_number, :images_size_validation

   belongs_to :user
   has_many :books, dependent: :destroy

  validates :title,
        presence: true,
        length: { minimum: 5, too_short: "%{count} characters is the minium"},
        length: { maximum: 60, too_long: "%{count} characters is the maximum"},
        case_sensitive: false

  validates :description,
            presence: true

  validates :address,
            presence: true

  validates :price,
            presence: true,
            numericality: { greater_than_or_equal_to: 1 }

  validates :artists_max,
          presence: true,
          numericality: { greater_than_or_equal_to: 1 }

  validates :images, presence: { message: "You need to add at least one image" }

  # Limit size of the image
  private def images_size_validation
    return if images.blank?
    images.each do |image|
      errors[:images] << "Should be less than 1 MO" if image.size > 1.megabytes
    end
  end

  private def images_limit_number 
    return if images.blank?
    errors[:images] << "You can't add more than 4 images" if images.size > 4
  end
end

app/controllers/users/workshops_controller.rb
class Users::WorkshopsController < WorkshopsController
  before_action :authenticate_user!

  def index
    @workshops = Workshop.where(user_id: current_user.id).limit(100)
  end
end

app/controllers/workshops/books_controller.rb
class Workshops::BooksController < BooksController 
  before_action :find_workshop!, only: [:new, :create]
  before_action :authenticate_user!

  def index
    select = 'workshops.title, workshops.price, books.id, books.total_price, books.start_date, books.end_date'
    @books_all = Book.select(select).joins('INNER JOIN workshops ON books.workshop_id = workshops.id').where(user_id: current_user.id).all
    @books_previous = Book.select(select).joins('INNER JOIN workshops ON books.workshop_id = workshops.id').where(user_id: current_user.id).where('end_date < ?', DateTime.now).all
    @books_coming = Book.select(select).joins('INNER JOIN workshops ON books.workshop_id = workshops.id').where(user_id: current_user.id).where('end_date > ?', DateTime.now).all
  end

  def show
    @book = Book.find(params[:id])
    @workshop = Workshop.find(@book.workshop_id)
  end

  def new 
    @title = 'Book an workshop'
    Book.where(workshop_id: @workshop.id).find_each do |book|
      @dates ||= []
      @dates.push({start: book.start_date, end: book.end_date})
    end 
    @dates = @dates.to_json
  end 

  def create
    total_price = (params[:end_date].to_i - params[:start_date].to_i) * @workshop.price
    @book = current_user.books.new(book_params.merge(total_price: total_price))
    if @book.save
      redirect_to :workshops_books_all
    else 
      redirect_to :workshops_new_book
    end
  end 

  def delete
    @book = Book.find(params[:id])
    @book.destroy
    respond_to do |format|
      format.html { redirect_to workshops_books_all_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def destroy
  end

  private 
    def find_workshop!
      @workshop = Workshop.where(id: params[:workshop_id]).first
      puts "Find workshop : " + @workshop.inspect
    end

    def book_params
      params.permit(:start_date, :end_date, :artists, :workshop_id)
    end
end

app/controllers/workshops/search_controller.rb
class Workshops::SearchController < SearchController

  def index
    if params[:keyword].empty?
      redirect_to :workshops
    else 
      @keyword = params[:keyword]
    end

    @workshops = Workshop.where('title LIKE ?', "%#{@keyword}%").limit(100)

    if @workshops.empty? 
      @no_results = 'There is no results for your query'
    end
  end

end

app/controllers/workshops_controller.rb
class WorkshopsController < ApplicationController
  before_action :set_workshop, only: [:show]

  # GET /workshops
  # GET /workshops.json
  def index
    @workshops = Workshop.all
  end

  # GET /workshops/new
  def new
    @workshop = Workshop.new
  end

  def edit 
    @workshop = Workshop.find(params[:id])
  end

  # POST /workshops
  # POST /workshops.json
  def create
    @workshop = current_user.workshops.new(workshop_params)

    respond_to do |format|
      if @workshop.save
        format.html { redirect_to @workshop, notice: 'Workshop was successfully created.' }
        format.json { render :show, status: :created, location: @workshop }
      else
        format.html { render new_users_workshop_path }
        format.json { render json: @workshop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workshops/1
  # PATCH/PUT /workshops/1.json
  def update
    @workshop = Workshop.find(params[:id])
    
    respond_to do |format|
      if @workshop.update(workshop_params)
        format.html { redirect_to @workshop, notice: 'Workshop was successfully updated.' }
        format.json { render :show, status: :ok, location: @workshop }
      else
        format.html { render :edit }
        format.json { render json: @workshop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workshops/1
  # DELETE /workshops/1.json
  def destroy
    @workshop = Workshop.find(params[:id])
    @workshop.destroy
    respond_to do |format|
      format.html { redirect_to users_workshops_url, notice: 'Workshop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  #   # Use callbacks to share common setup or constraints between actions.
    def set_workshop
      @workshop = Workshop.find(params[:id])
      @user = User.find(@workshop.user_id)
      @title = @workshop.title;
      puts 'User' + @user.inspect
    end

  #   # Never trust parameters from the scary internet, only allow the white list through.
    def workshop_params
      params.require(:workshop).permit(:title, :description, :address, :price, :lat, :lng, :artists_max, {images: []}, {art_types: []})
    end
end

app/helpers/workshops_helper.rb
module WorkshopsHelper
end

app/views/workshops/_form.html.erb
<%= form_with(model: workshop, local: true) do |form| %>
  <% if workshop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(workshop.errors.count, "error") %> prohibited this workshop from being saved:</h2>

      <ul>
      <% workshop.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :workshop_title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :workshop_description %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :workshop_address %>
  </div>

  <div class="field">
    <%= form.label :grade %>
    <%= form.text_field :grade, id: :workshop_grade %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :workshop_price %>
  </div>

  <div class="field">
    <%= form.label :images %>
    <%= form.file_field :images, multiple: true %>
  </div>
  <br>
  <div class="actions">
    <%= form.submit({:class => "btn"}) %>
  </div>
  <br>
<% end %>

app/views/workshops/index.html.erb
<div class="container">
  <%= content_tag(:div, notice, :class => "card-panel green darken-1 white-text") if notice %>
  
  <h1>Workshops in Paris</h1>
  
  <div class="row">
    <% @workshops.each_slice(3) do |group_workshops| %>
      <div class="row">
        <% group_workshops.each do |workshop| %>
          <div class="col s6 m4">
            <div class="card">
              <div class="card-image">
                <% if workshop.images.present? %>
                  <%= image_tag workshop.images.first %>
                <% else %>
                  <%= link_to(image_tag("photo.jpg")) %>
                <% end %>
              </div>
              <div class="card-title">
                <%= workshop.title %>
              </div>
              <div class="card-content">
                <%= workshop.description %>
              </div>
              <div class="card-action">
                <%= link_to 'See more', workshop_path(workshop) %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/workshops/show.html.erb
<% if @workshop.images.any? %>
  <div class="carousel carousel-slider">
    <% @workshop.images.each do |image| %>
      <% if image %>
        <a class="carousel-item"><%= image_tag(image, :class => "responsive-img") %></a>
      <% end %>
    <% end %>
  </div>
<% end %>

<div class="row">
  <div class="container">
    <%= content_tag(:div, notice, :class => "card-panel green darken-1 white-text") if notice %>
    <div class="col s8 m10">
      <div class="chip">
        <% if @user.avatar.present? %>
          <%= image_tag @user.avatar.thumb %>
        <% end %>
        <%= link_to @user.firstname + ' ' + @user.lastname, user_profile_path(@user) %>
      </div>
      
      <p>
        <strong>Title:</strong>
        <%= @workshop.title %>
      </p>

      <p>
        <strong>Types:</strong>
        <% @workshop.art_types.each do |type| %>
          <%= type %>
        <% end %>
      </p>
      
      <p>
        <strong>Description:</strong>
        <%= @workshop.description %>
      </p>
      
      <p>
        <strong>Address:</strong>
        <%= @workshop.address %>
      </p>

      <% if @workshop.artists_max.present? %>
        <p>
          <strong>Number of artists authorized at the same time :</strong>
          <%= @workshop.artists_max %>
        </p>
      <% end %>
      
      <% if @workshop.grade.present? %>
        <p>
          <strong>Grade:</strong>
          <%= @workshop.grade %>
        </p>
      <% end %>
      
      <p>
        <strong>Price:</strong>
        <%= @workshop.price %>€ per day
      </p>
      
      <% if @workshop.lat.present? && @workshop.lng.present? %>
        <span id="lng" class="hidden"><%= @workshop.lng %></span>
        <span id="lat" class="hidden"><%= @workshop.lat %></span>
        <div id="map"></div>
      <% end %>
    </div>
    <div class="col s4 m2 center">
      <% if current_user %>
        <% if @workshop.user_id === current_user.id %>
          <%= link_to 'Edit', edit_users_workshop_path(@workshop), :class => "btn" %>
        <% end %>
        <% if @workshop.user_id != current_user.id %>
          <%= link_to 'Book', workshops_new_book_path(@workshop), :class => "btn" %>
        <% end %>
      <% else  %>
        <%= link_to 'Book', workshops_new_book_path(@workshop), :class => "btn" %>
      <% end %>
    </div>
  </div>
</div>