config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'

  get 'errors/internal_server_error'

  devise_for :admins
  devise_for :users

  resources :workshops

  namespace :workshops do
    get ':workshop_id/books/new' => 'books#new', as: 'new_book'
    get 'books/all' => 'books#index'
    get 'book/:id' => 'books#show', as: 'show_book'
    delete 'book/:id' => 'books#delete'
    post ':workshop_id/books/new' => 'books#create'
    get 'search/results' => 'search#index'
  end

  get 'user/:id/profile' => 'users#show', as: 'user_profile'

  namespace :admin do 
    resources :users
  end

  namespace :users do
    resources :workshops
  end

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  root 'workshops#index', as: 'home'
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :lockable
  
  has_many :workshops
  has_many :books

  mount_uploader :avatar, AvatarUploader

  def book(workshop)
    workshop.inspect
    books.create(workshop: workshop)
  end
end

app/models/workshop.rb
class Workshop < ApplicationRecord
   mount_uploaders :images, WorkshopGalleryUploader
   validate :images_limit_number, :images_size_validation

   belongs_to :user
   has_many :books, dependent: :destroy

  validates :title,
        presence: true,
        length: { minimum: 5, too_short: "%{count} characters is the minium"},
        length: { maximum: 60, too_long: "%{count} characters is the maximum"},
        case_sensitive: false

  validates :description,
            presence: true

  validates :address,
            presence: true

  validates :price,
            presence: true,
            numericality: { greater_than_or_equal_to: 1 }

  validates :artists_max,
          presence: true,
          numericality: { greater_than_or_equal_to: 1 }

  validates :images, presence: { message: "You need to add at least one image" }

  # Limit size of the image
  private def images_size_validation
    return if images.blank?
    images.each do |image|
      errors[:images] << "Should be less than 1 MO" if image.size > 1.megabytes
    end
  end

  private def images_limit_number 
    return if images.blank?
    errors[:images] << "You can't add more than 4 images" if images.size > 4
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < UsersController 
  before_action :authenticate_admin!

  def index
    @users = User.all
    puts @users.inspect
  end

  def show
    @user = User.find(params[:id])
  end

  def edit 
  end

  # DELETE /workshops/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    respond_to do |format|
      format.html { redirect_to admin_users_path, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
end

app/controllers/users/workshops_controller.rb
class Users::WorkshopsController < WorkshopsController
  before_action :authenticate_user!

  def index
    @workshops = Workshop.where(user_id: current_user.id).limit(100)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show 
    @user = User.find(params[:id])
    @book = Book.where(user_id: params[:id]).to_a
    @workshop = Workshop.where(user_id: params[:id]).to_a
    @title = current_user.id.to_i == params[:id].to_i ? 'My profile' : 'Profile of ' + @user.firstname + ' ' + @user.lastname
  end
end

app/controllers/workshops/books_controller.rb
class Workshops::BooksController < BooksController 
  before_action :find_workshop!, only: [:new, :create]
  before_action :authenticate_user!

  def index
    select = 'workshops.title, workshops.price, books.id, books.total_price, books.start_date, books.end_date'
    @books_all = Book.select(select).joins('INNER JOIN workshops ON books.workshop_id = workshops.id').where(user_id: current_user.id).all
    @books_previous = Book.select(select).joins('INNER JOIN workshops ON books.workshop_id = workshops.id').where(user_id: current_user.id).where('end_date < ?', DateTime.now).all
    @books_coming = Book.select(select).joins('INNER JOIN workshops ON books.workshop_id = workshops.id').where(user_id: current_user.id).where('end_date > ?', DateTime.now).all
  end

  def show
    @book = Book.find(params[:id])
    @workshop = Workshop.find(@book.workshop_id)
  end

  def new 
    @title = 'Book an workshop'
    Book.where(workshop_id: @workshop.id).find_each do |book|
      @dates ||= []
      @dates.push({start: book.start_date, end: book.end_date})
    end 
    @dates = @dates.to_json
  end 

  def create
    total_price = (params[:end_date].to_i - params[:start_date].to_i) * @workshop.price
    @book = current_user.books.new(book_params.merge(total_price: total_price))
    if @book.save
      redirect_to :workshops_books_all
    else 
      redirect_to :workshops_new_book
    end
  end 

  def delete
    @book = Book.find(params[:id])
    @book.destroy
    respond_to do |format|
      format.html { redirect_to workshops_books_all_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def destroy
  end

  private 
    def find_workshop!
      @workshop = Workshop.where(id: params[:workshop_id]).first
      puts "Find workshop : " + @workshop.inspect
    end

    def book_params
      params.permit(:start_date, :end_date, :artists, :workshop_id)
    end
end

app/controllers/workshops/search_controller.rb
class Workshops::SearchController < SearchController

  def index
    if params[:keyword].empty?
      redirect_to :workshops
    else 
      @keyword = params[:keyword]
    end

    @workshops = Workshop.where('title LIKE ?', "%#{@keyword}%").limit(100)

    if @workshops.empty? 
      @no_results = 'There is no results for your query'
    end
  end

end

app/controllers/workshops_controller.rb
class WorkshopsController < ApplicationController
  before_action :set_workshop, only: [:show]

  # GET /workshops
  # GET /workshops.json
  def index
    @workshops = Workshop.all
  end

  # GET /workshops/new
  def new
    @workshop = Workshop.new
  end

  def edit 
    @workshop = Workshop.find(params[:id])
  end

  # POST /workshops
  # POST /workshops.json
  def create
    @workshop = current_user.workshops.new(workshop_params)

    respond_to do |format|
      if @workshop.save
        format.html { redirect_to @workshop, notice: 'Workshop was successfully created.' }
        format.json { render :show, status: :created, location: @workshop }
      else
        format.html { render new_users_workshop_path }
        format.json { render json: @workshop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workshops/1
  # PATCH/PUT /workshops/1.json
  def update
    @workshop = Workshop.find(params[:id])
    
    respond_to do |format|
      if @workshop.update(workshop_params)
        format.html { redirect_to @workshop, notice: 'Workshop was successfully updated.' }
        format.json { render :show, status: :ok, location: @workshop }
      else
        format.html { render :edit }
        format.json { render json: @workshop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workshops/1
  # DELETE /workshops/1.json
  def destroy
    @workshop = Workshop.find(params[:id])
    @workshop.destroy
    respond_to do |format|
      format.html { redirect_to users_workshops_url, notice: 'Workshop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  #   # Use callbacks to share common setup or constraints between actions.
    def set_workshop
      @workshop = Workshop.find(params[:id])
      @user = User.find(@workshop.user_id)
      @title = @workshop.title;
      puts 'User' + @user.inspect
    end

  #   # Never trust parameters from the scary internet, only allow the white list through.
    def workshop_params
      params.require(:workshop).permit(:title, :description, :address, :price, :lat, :lng, :artists_max, {images: []}, {art_types: []})
    end
end

app/helpers/workshops_helper.rb
module WorkshopsHelper
end

app/views/users/workshops/edit.html.erb
<div class="container">
  <h1>Editing Workshop</h1>
  
  <%= form_with(model: @workshop, local: true) do |form| %>
    <% if @workshop.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@workshop.errors.count, "error") %> prohibited this workshop from being saved:</h2>
  
        <ul>
        <% @workshop.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <%= form.label :title %>
      <%= form.text_field :title, id: :workshop_title %>
    </div>
  
    <div class="field">
      <%= form.label :description %>
      <%= form.text_area :description, id: :workshop_description %>
    </div>
  
    <div class="field">
      <%= form.label :address %>
      <%= form.text_field :address, id: :workshop_address %>
    </div>
  
    <div class="field">
      <%= form.label :grade %>
      <%= form.text_field :grade, id: :workshop_grade %>
    </div>
  
    <div class="field">
      <%= form.label :price %>
      <%= form.text_field :price, id: :workshop_price %>
    </div>

    <div class="field">
      <label>Number of artists accepted for one rental</label> 
      <%= form.number_field :artists_max %>
    </div>
  
    <div class="field">
      <% @workshop.images.each do |image, index| %>
        <div>
          <%= image_tag(image.thumb) %>
        </div>
      <% end %>
      <div class="file-field input-field">
        <div class="btn">
          <span>File</span>
          <%= form.file_field :images, multiple: true %>
        </div>
        <div class="file-path-wrapper">
          <input class="file-path validate" type="text">
        </div>
      </div>
    </div>
    <br>
    <div class="actions">
      <%= form.submit({:class => "btn"}) %>
    </div>
    <br>
  <% end %>
  
  
  <%= link_to 'Show', @workshop, :class => "btn" %>
  
</div>

app/views/users/workshops/index.html.erb
<div class="container workshop__page-index">
  <h1>My workshops</h1>
  
  <%= content_tag(:div, notice, :class => "card-panel green darken-1 white-text") if notice %>
  
  <% if @workshops.empty? %>
    <div class="card-panel">
      <span class="blue-text text-darken-2">
        <div>
          You have no workshops
        </div>
        <br>
        <div>
          <%= link_to 'Create an workshop', new_workshop_path, class: "btn" %>
        </div>
      </span>
    </div>
  <% else %>  
    <table class="striped">
      <thead>
        <tr>
          <th>Title</th>
          <th>Description</th>
          <th>Address</th>
          <th>Price</th>
          <th>Images</th>
          <th colspan="4"></th>
        </tr>
      </thead>
    
      <tbody>
        <% @workshops.each do |workshop| %>
          <tr>
            <td><%= workshop.title %></td>
            <td><%= workshop.description %></td>
            <td><%= workshop.address %></td>
            <td><%= workshop.price %></td>
            <td><%= workshop.images.count %></td>
             <ul id="dropdown3" class="dropdown-content">
              <li><%= link_to 'Show', workshop_path(workshop) %></li>
              <li><%= link_to 'Edit', edit_users_workshop_path(workshop) %></li>
              <li><%= link_to 'Destroy', users_workshop_path(workshop), method: :delete, data: { confirm: 'Are you sure?' }, :class => "red-text" %></li>
            </ul>
            <td>
              <a class="btn dropdown-button3" data-activates="dropdown3">
                Actions
              </a>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>  
</div>

app/views/users/workshops/new.html.erb
<div class="container workshop__page">
  <h1>New Workshop</h1>
  
  <%= form_with(model: @workshop, local: true) do |form| %>
  
    <% if @workshop.errors.any? %>
      <div class="card-panel red white-text">
        <h5><%= pluralize(@workshop.errors.count, "error") %> prohibited this workshop from being saved:</h5>
  
        <ul>
        <% @workshop.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <%= form.label :title %>
      <%= form.text_field :title, id: :workshop_title, "data-length" => "60" %>
    </div>

    <div class="field">
      <%= form.label :art_types %>
      <%= form.select(:art_types,
        [['Peinture', 'Peinture'], ['Plastique', 'Plastique'], ['Sculpture', 'Sculpture'], ['Street art', 'Street art'], ['Modelisme', 'Modelisme']],
        { },
        { multiple: true }) %>
    </div>
  
    <div class="field">
      <%= form.label :description %>
      <%= form.text_area :description, id: :workshop_description, class: "materialize-textarea" %>
    </div>
  
    <div class="field">
      <%= form.label :address %>
      <%= form.text_field :address, id: :workshop_address, class: "address" %>
    </div>
  
    <div class="field">
      <%= form.label :price %>
      <%= form.text_field :price, id: :workshop_price %>
    </div>

    <div class="field">
      <label>Number of artists accepted for one rental</label> 
      <%= form.number_field :artists_max %>
    </div>
  
     <div class="field">
      <%= form.hidden_field :lat, class: "lat" %>
      <%= form.hidden_field :lng, class: "lng" %>
    </div>
  

    <label>You can add multiple images by holding CTRL or CMD and click on the images (1mo max size per image)</label>
    <div class="field file-field input-field">
      <div class="btn">
        <span>Images</span>
        <%= form.file_field :images, multiple: true %>
      </div>
      <div class="file-path-wrapper">
        <input class="file-path validate" type="text">
      </div>
    </div>
    <br>
    <div class="actions">
      <%= form.submit(class: "btn") %>
    </div>
  <% end %>
</div>