config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'

  get 'errors/internal_server_error'

  devise_for :admins
  devise_for :users

  resources :workshops

  namespace :workshops do
    get ':workshop_id/books/new' => 'books#new', as: 'new_book'
    get 'books/all' => 'books#index'
    get 'book/:id' => 'books#show', as: 'show_book'
    delete 'book/:id' => 'books#delete'
    post ':workshop_id/books/new' => 'books#create'
    get 'search/results' => 'search#index'
  end

  get 'user/:id/profile' => 'users#show', as: 'user_profile'

  namespace :admin do 
    resources :users
  end

  namespace :users do
    resources :workshops
  end

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  root 'workshops#index', as: 'home'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_one :workshop

  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :lockable
  
  has_many :workshops
  has_many :books

  mount_uploader :avatar, AvatarUploader

  def book(workshop)
    workshop.inspect
    books.create(workshop: workshop)
  end
end

app/models/workshop.rb
class Workshop < ApplicationRecord
   mount_uploaders :images, WorkshopGalleryUploader
   validate :images_limit_number, :images_size_validation

   belongs_to :user
   has_many :books, dependent: :destroy

  validates :title,
        presence: true,
        length: { minimum: 5, too_short: "%{count} characters is the minium"},
        length: { maximum: 60, too_long: "%{count} characters is the maximum"},
        case_sensitive: false

  validates :description,
            presence: true

  validates :address,
            presence: true

  validates :price,
            presence: true,
            numericality: { greater_than_or_equal_to: 1 }

  validates :artists_max,
          presence: true,
          numericality: { greater_than_or_equal_to: 1 }

  validates :images, presence: { message: "You need to add at least one image" }

  # Limit size of the image
  private def images_size_validation
    return if images.blank?
    images.each do |image|
      errors[:images] << "Should be less than 1 MO" if image.size > 1.megabytes
    end
  end

  private def images_limit_number 
    return if images.blank?
    errors[:images] << "You can't add more than 4 images" if images.size > 4
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < UsersController 
  before_action :authenticate_admin!

  def index
    @users = User.all
    puts @users.inspect
  end

  def show
    @user = User.find(params[:id])
  end

  def edit 
  end

  # DELETE /workshops/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    respond_to do |format|
      format.html { redirect_to admin_users_path, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true

  before_action :account_update_permitted_parameters, :sign_in_permitted_parameters, if: :devise_controller?

  protected
    def account_update_permitted_parameters
      devise_parameter_sanitizer.permit(:account_update) do |user_params|
        user_params.permit(:firstname, :lastname, :current_password, :email, :password, :password_confirmation, :avatar, :phone, :description, :phone_visibility)
      end
    end

  protected
    def sign_in_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up) do |user_params|
        user_params.permit(:firstname, :lastname, :email, :password, :password_confirmation)
      end
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
  end

  def show
  end

  def create 
  end 
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def not_found
    @title = 'Page not found'
    render(:status => 404)
  end

  def internal_server_error
    @title = 'Internal error'
    render(:status => 500)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

end

app/controllers/users/workshops_controller.rb
class Users::WorkshopsController < WorkshopsController
  before_action :authenticate_user!

  def index
    @workshops = Workshop.where(user_id: current_user.id).limit(100)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show 
    @user = User.find(params[:id])
    @book = Book.where(user_id: params[:id]).to_a
    @workshop = Workshop.where(user_id: params[:id]).to_a
    @title = current_user.id.to_i == params[:id].to_i ? 'My profile' : 'Profile of ' + @user.firstname + ' ' + @user.lastname
  end
end

app/controllers/workshops_controller.rb
class WorkshopsController < ApplicationController
  before_action :set_workshop, only: [:show]

  # GET /workshops
  # GET /workshops.json
  def index
    @workshops = Workshop.all
  end

  # GET /workshops/new
  def new
    @workshop = Workshop.new
  end

  def edit 
    @workshop = Workshop.find(params[:id])
  end

  # POST /workshops
  # POST /workshops.json
  def create
    @workshop = current_user.workshops.new(workshop_params)

    respond_to do |format|
      if @workshop.save
        format.html { redirect_to @workshop, notice: 'Workshop was successfully created.' }
        format.json { render :show, status: :created, location: @workshop }
      else
        format.html { render new_users_workshop_path }
        format.json { render json: @workshop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workshops/1
  # PATCH/PUT /workshops/1.json
  def update
    @workshop = Workshop.find(params[:id])
    
    respond_to do |format|
      if @workshop.update(workshop_params)
        format.html { redirect_to @workshop, notice: 'Workshop was successfully updated.' }
        format.json { render :show, status: :ok, location: @workshop }
      else
        format.html { render :edit }
        format.json { render json: @workshop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workshops/1
  # DELETE /workshops/1.json
  def destroy
    @workshop = Workshop.find(params[:id])
    @workshop.destroy
    respond_to do |format|
      format.html { redirect_to users_workshops_url, notice: 'Workshop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  #   # Use callbacks to share common setup or constraints between actions.
    def set_workshop
      @workshop = Workshop.find(params[:id])
      @user = User.find(@workshop.user_id)
      @title = @workshop.title;
      puts 'User' + @user.inspect
    end

  #   # Never trust parameters from the scary internet, only allow the white list through.
    def workshop_params
      params.require(:workshop).permit(:title, :description, :address, :price, :lat, :lng, :artists_max, {images: []}, {art_types: []})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_controller_helper.rb
module BooksControllerHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" unless devise_error_messages?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      :count => resource.errors.count,
                      :resource => resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="card-panel red white-text">
      <h5>#{sentence}</h5>
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end

  def devise_error_messages?
    !resource.errors.empty?
  end

end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/search_workshops_helper.rb
module SearchWorkshopsHelper
end

app/helpers/workshops_helper.rb
module WorkshopsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Artishow <%= '- ' + @title if @title.present? %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'https://fonts.googleapis.com/icon?family=Material+Icons' %>
    <%= stylesheet_link_tag 'https://cdn.jsdelivr.net/bootstrap.daterangepicker/2/daterangepicker.css' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://code.jquery.com/jquery-3.2.1.min.js' %>
    <%= stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css' %>
    <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js' %>
    <%= javascript_include_tag 'https://cdn.jsdelivr.net/momentjs/latest/moment.min.js' %>
    <%= javascript_include_tag 'https://maps.googleapis.com/maps/api/js?key=AIzaSyDnc0ssO0jI_XbACaOYOBaW74m3YDPti_A&libraries=places' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://cdn.jsdelivr.net/bootstrap.daterangepicker/2/daterangepicker.js' %>
  </head>

  <ul id="slide-out" class="side-nav">
    <% if user_signed_in? %>
      <li>
        <div class="user-view">
          <div class="background blue-grey darken-4">
          </div>
          <div class="container__image">
            <%= image_tag current_user.avatar.medium %>
          </div>
          <span class="white-text name"> <%= current_user.firstname %> <%= current_user.lastname %> </span>
          <span class="white-text email"> <%= current_user.email %> </span>
        </div>
      </li>
        <li><%= link_to 'Home', home_path %></li>
        <li>
          <%= link_to 'Create a workshop', new_users_workshop_path %>
        </li>
        <li><%= link_to 'My profile', user_profile_path(current_user) %></li>
        <li><%= link_to 'My workshops', users_workshops_path %></li>
        <li><%= link_to 'My books', workshops_books_all_path %></li>
      <li>
        <%= link_to destroy_user_session_path, method: :delete do %>
          <i class="material-icons">power_settings_new</i> Log out
        <% end %>
      </li>
    <% else %>
      <li><%= link_to 'Home', home_path %></li>
      <li><%= link_to 'Log in', new_user_session_path %></li>
      <li><%= link_to 'Sign in', new_user_registration_path %></li>
    <% end %>
  </ul>

  <body>
    <div class="navbar-fixed">

    <%# User dropdown %>
    <ul id="user_submenu" class="dropdown-content">
      <li><%= link_to 'Profile', user_profile_path(current_user) if user_signed_in? %></li>
      <li class="divider"></li>
      <li><%= link_to 'My workshops', users_workshops_path %></li>
      <li class="divider"></li>
      <li><%= link_to 'My books', workshops_books_all_path %></li>
      <li class="divider"></li>
      <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
    </ul>

    <%# Admin dropdown %>
    <ul id="admin_submenu" class="dropdown-content">
      <li><%= link_to 'Profile', edit_admin_registration_path %></li>
      <li class="divider"></li>
      <li><%= link_to 'Log out', destroy_admin_session_path, method: :delete %></li>
    </ul>
      <nav>
        <a href="#" data-activates="slide-out" class="button-collapse"><i class="material-icons">menu</i></a>
        <div class="nav-wrapper">
          <%= link_to "Artishow", home_path, {:class => "brand-logo"} %>
          <ul id="nav-mobile" class="right hide-on-med-and-down">
            <li class="search__container">
              <%= form_tag(workshops_search_results_path, method: :get) do %>
                <%= text_field_tag :keyword, params[:keyword], :placeholder => "Search an workshop" %>
              <% end %>
            </li>
            <% if admin_signed_in? %>
              <li>
                <a class="dropdown-button1" href="#!" data-activates="admin_submenu">
                  Admin
                  <i class="material-icons right">arrow_drop_down</i>
                </a>
              </li>
              <li> <%= link_to 'Users', admin_users_path %> </li>
            <% end %>
            <% if user_signed_in? %>
              <li>
                <%= link_to 'Create a workshop', new_users_workshop_path %>
              </li>
              <li>
                <a class="dropdown-button2" data-activates="user_submenu">
                  <% if current_user.firstname && current_user.lastname %>
                    <%= current_user.firstname %> <%= current_user.lastname %>
                  <% else %>
                    <%= current_user.email %>
                  <% end %>
                  <i class="material-icons right">arrow_drop_down</i>
                </a>
              </li>
            <% else %>
              <% if admin_signed_in?.blank? %>
                <li><%= link_to 'Log in', new_user_session_path %></li>
                <li><%= link_to 'Sign in', new_user_registration_path %></li>
              <% end %>
            <% end %>
          </ul>
        </div>
      </nav>
    </div>

    <%= yield %>
    <%# <footer class="page-footer">
      <div class="footer-copyright">
        <div class="container">
          © 2017 Artishow
        </div>
      </div>
    </footer> %>
  </body>
</html>